### ISSUE TITLE
Can "scimath.units.unit_array.__newobj__" be removed?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/scimath#140]
Can `scimath.units.unit_array.__newobj__` be removed?

> Unpickles new-style objects.

"new-style" objects are the default objects on Python 3.

Ref https://github.com/enthought/scimath/blob/755f89e813077b213cdecb158d8ab980432d33f8/scimath/units/unit_array.py#L20-L23

**Comment by corranwebster** [comment]
Yes, I think this is still needed - it is used here:
https://github.com/enthought/scimath/blob/755f89e813077b213cdecb158d8ab980432d33f8/scimath/units/unit_array.py#L100-L110
and `__newobj__` is treated magically by the pickle system: https://www.python.org/dev/peps/pep-0307/#id20

I think it's needed because we are subclassing `ndarray` (although the comment talks about tuples, so it _might_ not be needed).

This is deep magic, so if it is working, don't mess with it without _lots_ of tests and a solid understanding of what it is doing and why.

**Comment by rahulporuri** [comment]
Thanks for that @corranwebster . We definitely don't have the time to investigate this that thoroughly. Closing.
